### PR TITLE
fix(zh.picacomic): search related not working properly

### LINKED ISSUE #183: Picacomic search not working
Image
Image
Image

some tags in official app filters (like NTR, 純愛) can be searched by clicking tags
but the search bar returns nothing

### PR DESCRIPTION
**Pull request by dyphire**
And add missing token expiration refresh mechanism

Fix #183

### CODE REVIEW

File: sources/zh.picacomic/src/home.rs [hunk 1]
```diff
@@ -110,7 +110,18 @@ impl Home for Picacomic {
 				.map_err(|_| error!("Failed to convert responses to array"))?;
 
 		let results: [Result<MangaPageResult>; 8] = responses.map(|res| {
-			let json: serde_json::Value = res?.get_json()?;
+			let mut response = res?;
+			let json: serde_json::Value = response.get_json()?;
```
Comment (kkantan) [inline sources/zh.picacomic/src/home.rs]: there's no need to parse the response as a json if the status is 401, you should define this after the if branch.

File: sources/zh.picacomic/src/json/mod.rs [hunk 2]
```diff
@@ -145,10 +152,33 @@ impl From<ComicItem> for Manga {
...
+			.pages_count
+			.map_or(String::new(), |count| format!("页数：{}P", count));
+		let likes_text = item
+			.total_likes
+			.or(item.likes_count)
+			.map_or(String::new(), |count| format!("{} likes", count));
+
+		let mut desc_parts = Vec::new();
+
+		if !likes_text.is_empty() {
```
Comment (kkantan) [inline sources/zh.picacomic/src/json/mod.rs]: you should use an `Option<String>` instead of checking if it's empty, to avoid extra allocation

File: sources/zh.picacomic/src/json/mod.rs [hunk 3]
```diff
@@ -145,10 +152,33 @@ impl From<ComicItem> for Manga {
...
+		}
+
+		if !pages_text.is_empty() {
+			desc_parts.push(pages_text);
+		}
+
+		if let Some(desc) = item.description
+			&& !desc.trim().is_empty() {
+				desc_parts.push(format!("简介：{}", desc));
+			}
```
Comment (kkantan) [inline sources/zh.picacomic/src/json/mod.rs]: this doesn't look like standard `rustfmt` formatting

File: sources/zh.picacomic/src/net/mod.rs [hunk 4]
```diff
@@ -198,8 +196,12 @@ impl Display for Url {
 					gen_explore_url(category.to_string(), sort.to_string(), *page)
 				)
 			}
-			Url::Search { query: _, page } => {
-				write!(f, "{}/comics/advanced-search?page={}&s=dd", API_URL, page)
+			Url::Search {
+				query: _,
+				sort: _,
+				page,
+			} => {
```
Comment (kkantan) [inline sources/zh.picacomic/src/net/mod.rs]:
```suggestion
			Url::Search { page, .. } => {
```

File: sources/zh.picacomic/src/home.rs (hunk 1 above)
Comment (dyphire) [reply sources/zh.picacomic/src/home.rs]: Done

File: sources/zh.picacomic/src/json/mod.rs (hunk 2 above)
Comment (dyphire) [reply sources/zh.picacomic/src/json/mod.rs]: Done

File: sources/zh.picacomic/src/json/mod.rs (hunk 3 above)
Comment (dyphire) [reply sources/zh.picacomic/src/json/mod.rs]: Done

File: sources/zh.picacomic/src/home.rs [hunk 5]
```diff
@@ -110,7 +110,18 @@ impl Home for Picacomic {
...
-			let json: serde_json::Value = res?.get_json()?;
+			let mut response = res?;
+
+			// Check for 401 and retry with new login if needed
+			if response.status_code() == 401 {
+				// Re-login
+				crate::net::login()?;
+				// Retry the request - but since we have multiple requests, we need to handle this differently
+				// For simplicity, we'll just return an error for now, but ideally we'd retry each request
+				return Err(error!("Authentication expired, please try again"));
```
Comment (kkantan) [inline sources/zh.picacomic/src/home.rs]:
```suggestion
				bail!("Authentication expired, please try again");
```

**Review by kkantan — CHANGES_REQUESTED** [review]

File: sources/zh.picacomic/src/home.rs (hunk 5 above)
Comment (dyphire) [reply sources/zh.picacomic/src/home.rs]: Done

**Review by kkantan — APPROVED** [review]
