### PR TITLE
fix(libgroup): chapters not loading

### LINKED ISSUE #460: hentailib.me
No title from hentailib does not open, it gives a network error, although there is authorization and access to the site is also available, because if you click on the button to open the chapter in the browser, everything works immediately. The problem has been going on for 2-3 weeks

Image

### LINKED ISSUE #476: mangalib.me Doesn't load the list of chapters
image
image

### PR DESCRIPTION
**Pull request by remytomme**
- Add `ResponseJsonExt::parse_json` that includes a 300-char context window around the error column.
- Fix `summary` field: API changed from plain string to ProseMirror document (`{"type":"doc","content":[...]}`). Now deserializes as `LibGroupContentModel` and converts through the existing `convert_model_to_markdown` converter.
- Bump versions for all four LibGroup sources.

Closes #460, #476

### CODE REVIEW

File: templates/libgroup/src/json.rs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+			let context: String = core::str::from_utf8(&bytes)
+				.unwrap_or("<non-utf8>")
+				.chars()
+				.skip(start)
+				.take(300)
+				.collect();
+			AidokuError::message(format!(
+				"JSON error at col {col} (body {} bytes): {e} | context: ...{context}...",
+				bytes.len()
+			))
```
Comment (kkantan) [inline templates/libgroup/src/json.rs:28]: you could just use the shorthand macro for this.
```suggestion
			error!(
				"JSON error at col {col} (body {} bytes): {e} | context: ...{context}...",
				bytes.len()
			)
```

**Review by kkantan — APPROVED** [review]
